apiVersion: 1

groups:
  - name: GPU Alerts
    folder: GPU Monitoring
    interval: 1m
    rules:
      - name: High GPU Temperature
        condition: gpu_temperature_celsius > 85
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: GPU temperature is high
          description: GPU temperature has been above 85°C for 5 minutes

      - name: GPU Memory Near Capacity
        condition: (gpu_memory_used_mb / gpu_memory_total_mb * 100) > 90
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: GPU memory usage high
          description: GPU memory usage has been above 90% for 2 minutes

      - name: High GPU Utilization
        condition: gpu_utilization > 95
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: GPU utilization very high
          description: GPU utilization has been above 95% for 10 minutes

      - name: CUDA Errors Increasing
        condition: rate(gpu_cuda_errors_total[5m]) > 0
        labels:
          severity: critical
        annotations:
          summary: CUDA errors detected
          description: There are new CUDA errors being reported