# Location: E:/justica/docker/docker-compose.yml

version: '3.8'

x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "100m"
    max-file: "5"
    compress: "true"

services:
  nginx:
    container_name: justica_nginx
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ../config/services/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - ai_server
      - grafana
    restart: unless-stopped
    networks:
      - frontend
      - backend
    logging: *default-logging

  ai_server:
    container_name: justica_ai_server
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - CUDA_VISIBLE_DEVICES=0
      - NVIDIA_REQUIRE_CUDA=cuda>=11.8
      - PYTHONUNBUFFERED=1
      - AI_DATA_PATH=${AI_DATA_PATH}
      - MODEL_CACHE_PATH=${MODEL_CACHE_PATH}
    volumes:
      - ../:/app:ro
      - ai_data:/data
      - model_cache:/app/model_cache
      - cuda_cache:/cuda-cache
    expose:
      - "8000"
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 16G
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    networks:
      - backend
    restart: unless-stopped
    logging: *default-logging
    healthcheck:
      test: ["CMD", "python3", "-c", "import torch; assert torch.cuda.is_available()"]
      interval: 30s
      timeout: 10s
      retries: 3

  grafana:
    container_name: justica_grafana
    image: grafana/grafana:latest
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - GF_USERS_DEFAULT_THEME=dark
      - GF_AUTH_ANONYMOUS_ENABLED=false
    volumes:
      - grafana_data:/var/lib/grafana
    expose:
      - "3000"
    networks:
      - backend
    restart: unless-stopped
    logging: *default-logging
    depends_on:
      - prometheus

  redis:
    container_name: justica_redis
    image: redis:alpine
    command: redis-server --requirepass ${REDIS_PASSWORD}
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    expose:
      - "6379"
    networks:
      - backend
    restart: unless-stopped
    logging: *default-logging
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  prometheus:
    container_name: justica_prometheus
    image: prom/prometheus:latest
    volumes:
      - ../config/prometheus:/etc/prometheus:ro
      - prometheus_data:/prometheus
    expose:
      - "9090"
    networks:
      - backend
    restart: unless-stopped
    logging: *default-logging

networks:
  frontend:
  backend:

volumes:
  ai_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${AI_DATA_PATH}
  model_cache:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${MODEL_CACHE_PATH}
  cuda_cache:
  redis_data:
  grafana_data:
  prometheus_data: