# Location: E:/justica/docker/docker-compose.yml

services:
  nginx:
    container_name: justica_nginx
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ../config/services/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - backend
    restart: unless-stopped

  ai_server:
    container_name: justica_ai_server
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      - NVIDIA_VISIBLE_DEVICES=0
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,graphics
      - CUDA_VISIBLE_DEVICES=0
    runtime: nvidia
    ports:
      - "8000:8000"
      - "8001:8001"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    networks:
      - backend
    restart: unless-stopped

  redis:
    container_name: justica_redis
    image: redis:alpine
    command: redis-server --requirepass As!101010
    ports:
      - "6379:6379"
    networks:
      - backend
    restart: unless-stopped

  grafana:
    container_name: justica_grafana
    image: grafana/grafana:latest
    environment:
      - GF_SECURITY_ADMIN_USER=fixola
      - GF_SECURITY_ADMIN_PASSWORD=As!101010
      - GF_USERS_DEFAULT_THEME=dark
      - GF_AUTH_ANONYMOUS_ENABLED=false
    ports:
      - "3000:3000"
    networks:
      - backend
    restart: unless-stopped

  prometheus:
    container_name: justica_prometheus
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    networks:
      - backend
    restart: unless-stopped

networks:
  backend: