api_rate_limiting:
  enabled: true
  rate: ${RATE_LIMIT_PER_MINUTE}
  per: minute
  burst: 5

cors:
  allowed_origins:
    - https://api.statista.live
    - https://monitor.statista.live
  allowed_methods:
    - GET
    - POST
    - PUT
    - DELETE
  allowed_headers:
    - Authorization
    - Content-Type
  max_age: 3600

ssl:
  enabled: true
  min_version: TLSv1.2
  ciphers:
    - ECDHE-ECDSA-AES128-GCM-SHA256
    - ECDHE-RSA-AES128-GCM-SHA256
    - ECDHE-ECDSA-AES256-GCM-SHA384
    - ECDHE-RSA-AES256-GCM-SHA384

auth:
  jwt_expiry: 3600
  refresh_token_expiry: 604800
  password_hash_algorithm: bcrypt
  password_hash_rounds: 12