# config/prometheus/web.yml
basic_auth_users:
  ${PROMETHEUS_BASIC_AUTH_USER}: ${PROMETHEUS_BASIC_AUTH_PASS_HASH}  # Use bcrypt hash

tls_server_config:
  cert_file: /etc/prometheus/certs/prometheus.crt
  key_file: /etc/prometheus/certs/prometheus.key

http_config:
  http2: true